# Generated by Django 5.1.4 on 2025-03-26 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop')], default='desktop', max_length=20)),
                ('specification', models.TextField(blank=True, null=True)),
                ('components', models.TextField()),
                ('spare', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.assignee')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.computer')),
            ],
        ),
    ]
