# Generated by Django 5.1.4 on 2025-03-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computer.assignee'),
        ),
        migrations.DeleteModel(
            name='ComputerAssignment',
        ),
    ]
