# Generated by Django 5.1.4 on 2025-03-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_computer_assignee_delete_computerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
