# Generated by Django 5.1.4 on 2025-03-26 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_computer_assigned_at_computer_returned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computer.assignee')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='computer.computer')),
            ],
        ),
    ]
