# Generated by Django 5.1.4 on 2025-03-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_computerhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='returned_at',
        ),
    ]
