# Generated by Django 5.1.4 on 2025-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_remove_computer_assigned_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerhistory',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='computerhistory',
            name='returned_at',
        ),
        migrations.AddField(
            model_name='computerhistory',
            name='action',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='computerhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
